services:
  backend:
    build: ./back
    ports:
      - 5000:5000
    environment:
      - JWT_SECRET=secret
    networks:
      - erickgcastro-ms-crud-t

  frontend:
    build: ./front
    ports:
      - 3000:3000
    env_file:
      - ./front/.env
    depends_on:
      - backend
    networks:
      - erickgcastro-ms-crud-t
networks:
  erickgcastro-ms-crud-t:
